AIInterviewBot/AIInterviewBot/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import accounts.views as accounts
import contents.views as contents

urlpatterns = [
    # 管理後台
    path('admin/', admin.site.urls),

    # ----------套件 start----------
    
    # 驗證碼
    path('captcha/', include('captcha.urls')),
    #django-allauth
    path('accounts/', include('allauth.urls')),

    # ----------套件 end----------

    # ----------accounts start----------

    # 首頁
    path('', accounts.index, name='Index'),
    # 登入
    path('login/', accounts.sign_in, name='Login'),
    # 登出
    path('logout/',accounts.log_out, name='Logout'),
    # 註冊
    path('register/', accounts.register, name='Register'),
    # 忘記密碼頁面
    path('forgot_password/', accounts.forgot_password, name='ForgotPassword'),
    # 個人檔案頁面
    path('personal/', accounts.personal, name='Personal'),
    # 密碼重設確認頁面
    path('reset/confirm/<uidb64>/<token>/', accounts.password_reset_confirm, name='PasswordResetConfirm'),
    # 密碼重設完成頁面
    path('reset/complete/', accounts.password_reset_complete, name='PasswordResetComplete'),
    # 修改密碼
    path('change_password/', accounts.change_password, name='ChangePassword'),
    # 幫助中心
    path('help_center/', accounts.help_center, name='HelpCenter'),
    # 問題回報
    path('problem_report/', accounts.problem_report, name='ProblemReport'),

    # ----------accounts end------------

    # ----------contents start----------
    
    # 自我介紹
    path('self_introduction/', contents.self_introduction, name='SelfIntroduction'),
    # 求職信
    path('cover_letter/', contents.cover_letter, name='CoverLetter'),
    path('<str:type>/result/', contents.content_result, name='ContentResult'),
    # 推薦信
    path('recommendation_letter/', contents.recommendation_letter, name='RecommendationLetter'),
    # 簡歷
    path('resume/', contents.resume, name='Resume'),
    path('api/download_file/', contents.download_file, name='DownloadFile'),
    # 模擬面試
    path('mock_interview_mode/', contents.mock_interview_mode, name='MockInterviewMode'),
    path('mock_interview/<str:mode>/', contents.mock_interview, name='MockInterview'),
    path('mock_interview_result/', contents.mock_interview_result, name='MockInterviewResult'),
    # 儀錶板
    path('dashboard/', contents.dashboard, name='Dashboard'),
    path('api/get_chart_data/', contents.get_chart_data, name='GetChartData'),
    # 歷史紀錄首頁
    path('history/', contents.history, name='History'),
    # 歷史紀錄詳細頁面
    path('history/detail/', contents.history_detail, name='HistoryDetail'),

    # ----------contents end------------
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AIInterviewBot/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from contents.models import DashBoard

User = settings.AUTH_USER_MODEL

# 使用者資料
class UserProfile(AbstractUser):
    profile_image = models.ImageField(upload_to='profile_images/',blank=True, null=True)
    GENDER_CHOICES = (
        ('M', '男性'),
        ('F', '女性'),
        ('O', '其他'),
    )
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=True, null=True)
    birth_date = models.DateField(blank=True,null=True)
    DEGREE_CHOICES = (
        ('S', '高中'),
        ('B', '學士'),
        ('M', '碩士'),
        ('D', '博士'),
    )
    degree = models.CharField(max_length=100, choices=DEGREE_CHOICES, blank=True, null=True)

# 當使用者註冊時，自動建立一個Dashboard
@receiver(post_save, sender=User)
def create_user_dashboard(sender, instance, created, **kwargs):
    if created:
        DashBoard.objects.create(user=instance)

# 問題回報
class ProblemReport(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    TYPE_CHOICES = (
        ('A', '帳號問題'),
        ('T', '技術問題'),
        ('O', '其他問題'),
    )
    type = models.CharField(max_length=1, choices=TYPE_CHOICES)
    problem = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username + "-" + self.type

AIInterviewBot/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from .models import ProblemReport
from captcha.fields import CaptchaField
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.forms import SetPasswordForm
from django.contrib.auth import get_user_model, authenticate

User = get_user_model()


class RegisterForm(UserCreationForm):

  error_messages = {
      "password_mismatch": _("密碼驗證錯誤，請重新輸入"),
  }

  username = forms.CharField(
      label="帳號",
      error_messages={'unique': '此使用者名稱已被使用'},
      widget=forms.TextInput(attrs={
          'class': 'form-control',
          'style': 'margin-left: 5px;'
      }))

  email = forms.EmailField(
      label="電子郵件",
      widget=forms.EmailInput(attrs={
          'class': 'form-control',
          'style': 'margin-left: 5px;'
      }))

  password1 = forms.CharField(
      label="密碼",
      widget=forms.PasswordInput(attrs={
          'class': 'form-control',
          'style': 'margin-left: 5px;'
      }))

  password2 = forms.CharField(
      label="密碼確認",
      widget=forms.PasswordInput(attrs={
          'class': 'form-control',
          'style': 'margin-left: 5px;'
      }))

  class Meta:
    model = User
    fields = ('username', 'email', 'password1', 'password2')

  def clean(self):
    email = self.cleaned_data.get('email')
    if User.objects.filter(email=email).exists():
      raise ValidationError("此電子郵件已被註冊過")
    # TODO:跳出email重複錯誤訊息
    return self.cleaned_data


class LoginForm(forms.Form):

  error_messages = {"invalid_login": _("帳號或密碼錯誤")}

  username = forms.CharField(
      label="帳號",
      widget=forms.TextInput(attrs={
          'class': 'form-control login-label',
          'style': 'width: 100%;'
      }))

  password = forms.CharField(
      label="密碼",
      widget=forms.PasswordInput(attrs={
          'class': 'form-control login-label',
          'style': 'width: 90%;'
      }))

  captcha = CaptchaField(label="驗證碼", error_messages={"invalid": "驗證碼錯誤"})

  remember_me = forms.BooleanField(label="保持登入",
                                   required=False,
                                   widget=forms.CheckboxInput())

  def clean_data(self):
    username = self.cleaned_data.get('username')
    password = self.cleaned_data.get('password')
    user = authenticate(username=username, password=password)
    if not user:
      raise forms.ValidationError("invalid_login")
    # TODO:跳出帳號/密碼錯誤的訊息
    return self.cleaned_data


# 修改密碼
class ChangePasswordForm(PasswordChangeForm):

  error_messages = {
      **SetPasswordForm.error_messages,
      "password_incorrect": _("舊密碼輸入錯誤，請重新輸入"),
      "password_mismatch": _("密碼驗證錯誤，請重新輸入"),
  }
  old_password = forms.CharField(
      label="舊密碼",
      widget=forms.PasswordInput(
          attrs={
              "autocomplete": "new-password",
              'style': 'width: 90%; margin-left: 15px;'
          }))
  new_password1 = forms.CharField(
      label="新密碼",
      widget=forms.PasswordInput(
          attrs={
              "autocomplete": "new-password",
              'style': 'width: 90%; margin-left: 15px;'
          }))
  new_password2 = forms.CharField(
      label="新密碼確認",
      widget=forms.PasswordInput(
          attrs={
              "autocomplete": "new-password",
              'style': 'width: 90%; margin-left: 15px;'
          }))


# 忘記密碼
class ForgotPasswordForm(forms.Form):

  email = forms.EmailField(
      label="電子郵件",
      widget=forms.EmailInput(attrs={
          'class': 'form-control',
          'style': 'margin-left: 6px;'
      }))


GENDER_CHOICES = (
    ('', '請選擇性別'),
    ('M', '男性'),
    ('F', '女性'),
    ('O', '其他'),
)
DEGREE_CHOICES = (
    ('', '請選擇學位'),
    ('S', '高中'),
    ('B', '學士'),
    ('M', '碩士'),
    ('D', '博士'),
)


# 個人檔案
class PersonalForm(ModelForm):
  gender = forms.ChoiceField(
      choices=GENDER_CHOICES,
      widget=forms.Select(attrs={
          'class': 'form-control',
          'style': 'text-align: right;',
          'disabled': ''
      }),
      required=False)
  degree = forms.ChoiceField(
      choices=DEGREE_CHOICES,
      widget=forms.Select(attrs={
          'class': 'form-control',
          'style': 'text-align: right;',
          'disabled': ''
      }),
      required=False)

  class Meta:
    model = User
    fields = ('profile_image', 'gender', 'birth_date', 'degree')
    widgets = {
        'profile_image':
        forms.FileInput(
            attrs={
                'class': 'form-control',
                'id': 'photo',
                'accept': 'image/*',
                'style': 'display: none;'
            }),
        'birth_date':
        forms.DateInput(
            attrs={
                'type': 'date',
                'class': 'form-control',
                'style': 'text-align: right; margin-left: 20px;',
                'disabled': ''
            }),
    }


TYPE_CHOICES = (('', '請選擇問題類型'), ('A', '帳號問題'), ('T', '技術問題'), ('O', '其他問題'))


# 問題回報
class ProblemReportForm(ModelForm):
  type = forms.ChoiceField(
      choices=TYPE_CHOICES,
      widget=forms.Select(attrs={'class': 'form-control'}))

  class Meta:
    model = ProblemReport
    fields = ('type', 'problem')
    widgets = {
        'problem':
        forms.Textarea(
            attrs={
                'class': 'form-control',
                'placeholder': '遇到問題了嗎?若無法在幫助中心找到相關的解決方式，請在此簡單敘述您遇到的問題。',
                'style': 'resize:none; background-color: #ffffff;'
            }),
    }

AIInterviewBot/accounts/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from accounts.forms import RegisterForm , LoginForm, ForgotPasswordForm, ChangePasswordForm, PersonalForm, ProblemReportForm
from django.contrib.auth import get_user_model
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from django.core.mail import EmailMessage, send_mail
from django.conf import settings
from django.template.loader import render_to_string

from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str

from django.contrib import messages
from django.contrib.auth.forms import SetPasswordForm
from django.contrib.auth import get_user_model
User = get_user_model()
from django.core.files import File
from tempfile import TemporaryFile
from allauth.socialaccount.models import SocialAccount
from accounts.models import UserProfile
from contents.models import DashBoard
import urllib.request


# 首頁
@login_required(login_url="Login")
def index(request): 
    user = request.user
    profile_image_url = '/static/images/user_default.png'  # 預設圖片 URL
    try:
        # URL抓取圖片
        if not user.profile_image:
            social_account = SocialAccount.objects.get(user=user.id)
            social_account_name = social_account.extra_data.get('name')
            picture_url = social_account.extra_data.get('picture')
            temp_image = TemporaryFile()
            with urllib.request.urlopen(picture_url) as response:
                temp_image.write(response.read())
            temp_image.flush()
            profile = UserProfile.objects.get(id=user.id)
            profile.profile_image.save(social_account_name + ".png", File(temp_image))
            profile.save()
            unit = UserProfile.objects.get(id=user.id)
            profile_image_url = unit.profile_image.url
    except SocialAccount.DoesNotExist:
        pass
    request.session['picture_url'] = profile_image_url
    return render(request, 'accounts/index.html')

# 登入
def sign_in(request):
    if request.user.is_authenticated:
        return redirect('/')  # 如果使用者已經登入，直接導向首頁
    
    if request.method == "POST":
        loginForm = LoginForm(request.POST) 
        if loginForm.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password")
            remember_me = request.POST.get("remember_me")
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                if not remember_me:
                    request.session.set_expiry(0)
                return redirect('/')  # 導向到首頁
    else:
        loginForm = LoginForm()

    return render(request, 'accounts/login.html', locals())


# 登出
def log_out(request):
    logout(request)
    return redirect('/')
  
# 註冊
def register(request):
    # 如果使用者已經登入，直接導向首頁
    if request.user.is_authenticated:
        return redirect('/')
    
    registerForm = RegisterForm()
    if request.method == "POST":
        registerForm = RegisterForm(request.POST)
        if registerForm.is_valid():
            
            # 儲存 User 物件到資料庫並取得已創建的 User 物件
            user = registerForm.save()

            try:
                # 電子郵件內容樣板
                email_template = render_to_string(
                    'accounts/signup_success_email.html',
                    {'username': request.user.username}
                )

                email = EmailMessage(
                    '註冊成功通知信',  # 電子郵件標題
                    email_template,  # 電子郵件內容
                    settings.EMAIL_HOST_USER,  # 寄件者
                    [request.POST.get("email")]  # 收件者
                )

                email.fail_silently = False
                email.send()
            except:
                pass

            return render(request, 'accounts/register.html', {'registration_success': True})
    return render(request, 'accounts/register.html', locals())

#忘記密碼頁面
def forgot_password(request):
    forgotPasswordForm = ForgotPasswordForm()
    if request.method == 'POST':
        email = request.POST['email']
        try:
            user = User.objects.get(email=email)
            # 生成一個隨機的密碼重置令牌
            token = default_token_generator.make_token(user)
            # 將令牌和使用者資訊保存到資料庫
            user.reset_password_token = token
            user.save()
            # 發送包含重置連結的電子郵件

            uidb64 = urlsafe_base64_encode(force_bytes(user.pk))
            reset_link = request.build_absolute_uri('/reset/confirm/'+ uidb64 + '/' + token)
            send_mail(
                '密碼重置請求',
                '請點擊以下連結來重置您的密碼: ' + reset_link,
                settings.EMAIL_HOST_USER,  # 寄件者
                [email],
                fail_silently=False,
            )
            return render(request, 'accounts/email_success.html')
        except User.DoesNotExist:
            return render(request, 'accounts/email_error.html')
    return render(request, 'accounts/forgot_password.html', locals())
  
#修改密碼
@login_required(login_url="Login")
def change_password(request):
    user = request.user
    if request.method == 'POST':
        changePasswordForm = ChangePasswordForm(request.user,request.POST)
        if changePasswordForm.is_valid():
            user = changePasswordForm.save()
            update_session_auth_hash(request, user)
            success = True
    else:
        changePasswordForm = ChangePasswordForm(request.user)
    return render(request, 'accounts/change_password.html', locals())

#使用者收信後的連結頁面
def password_reset_confirm(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        # 顯示密碼重設表單
        form = SetPasswordForm(user=user)
        if request.method == 'POST':
            form = SetPasswordForm(user=user, data=request.POST)
            if form.is_valid():
                form.save()
                user.reset_password_token = None
                user.save()
                success = True

        return render(request, 'accounts/reset_password_confirm.html', locals())
    else:
        urlExpired = True
        return redirect(reverse('ForgotPassword'), locals())
        # return HttpResponse('<script>alert("密碼重設連結無效或已過期。"); window.location.href = "/forgot_password";</script>')
        
#密碼重設成功頁面
def password_reset_complete(request):
    return render(request, 'accounts/reset_password_complete.html')
  
#個人檔案頁面
@login_required(login_url="Login")
def personal(request):
    unit = User.objects.get(id=request.user.id)
    if request.method == 'POST':
        form = PersonalForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect(reverse('Personal'))
    else:
        dashboard = DashBoard.objects.get(id=request.user.id)
        form = PersonalForm(instance=unit)
    return render(request, 'accounts/personal.html', locals())

#幫助中心頁面
@login_required(login_url="Login")
def help_center(request):
    return render(request, 'accounts/help_center.html')

#問題回報頁面
@login_required(login_url="Login")
def problem_report(request):
    if request.method == 'POST':
        form = ProblemReportForm(request.POST)
        if form.is_valid():
            problem_report = form.save(commit=False)
            problem_report.user = request.user
            problem_report.save()
            success = True
    else:
        form = ProblemReportForm()
    return render(request, 'accounts/problem_report.html', locals())

AIInterviewBot/templates/accounts/AccountsBase.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% load static %}
  <meta charset="utf-8">
  <link rel="stylesheet" type="text/css" href="{% static 'css/accounts.css' %}" />
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
    integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.7.0.min.js"
    integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous">
  </script>
</head>

<body>
  {% block content %}
  {% endblock %}
  <!-- Option 1: Bootstrap Bundle (includes Popper) -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous">
  </script>
</body>

</html>

AIInterviewBot/templates/accounts/change_password.html
{% extends "Base.html" %}
{% block title %}變更密碼{% endblock %}
{% block content %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/changePassword.css' %}" />

<div class="center" style="box-shadow: none; margin-top: 30px;">
	<div style="text-align: center; margin-bottom: 0px; margin-bottom: 50px;">
        <img src="{% static 'images/LOGO.png' %}" alt="LOGO" width="90" height="108" >
    </div>
	<h1 style="text-align: left; padding-left: 40px; font-size: 25px; padding-top: 0px; padding-bottom: 0px; margin-top: 100px; font-weight: 600;">變更密碼</h1>
	<form method="post" id="change-password-form">
		{% csrf_token %}
		<div class="txt_field">
			<img src="{% static 'images/lock.png' %}" alt="lock" width="18px" height="18px" style="position: absolute; margin-top: 10px; margin-left: -2px;">
			<label for="{{ changePasswordForm.old_password.id_for_label }}"></label>
			{{ changePasswordForm.old_password }}
			<label style="margin-left: 17px;">{{ changePasswordForm.old_password.label }}</label>
			<button type="button" id="old_password_eye" style="margin-left: 5px; border: transparent; background-color: transparent; position: absolute; margin-left: -5px; margin-top: 7px;">
				<img src="{% static 'images/eye-slash-solid.png' %}" alt="顯示密碼" width="20" height="20">
			</button>
		</div>
		<div class="txt_field">
			<img src="{% static 'images/lock.png' %}" alt="lock" width="18px" height="18px" style="position: absolute; margin-top: 10px; margin-left: -2px;">
			<label for="{{ changePasswordForm.new_password1.id_for_label }}"></label>
			{{ changePasswordForm.new_password1 }}
			<label style="margin-left: 17px;">{{ changePasswordForm.new_password1.label }}</label>
			<button type="button" id="new_password1_eye" style="margin-left: 5px; border: transparent; background-color: transparent; position: absolute; margin-left: -5px; margin-top: 7px; ">
				<img src="{% static 'images/eye-slash-solid.png' %}" alt="顯示密碼" width="20" height="20">
			</button>
		</div>
		<div class="txt_field">
			<img src="{% static 'images/lock.png' %}" alt="lock" width="18px" height="18px" style="position: absolute; margin-top: 10px; margin-left: -2px;">
			<label for="{{ changePasswordForm.new_password2.id_for_label }}"></label>
			{{ changePasswordForm.new_password2 }}
			<label style="margin-left: 17px;">{{ changePasswordForm.new_password2.label }}</label>
			<button type="button" id="new_password2_eye" style="margin-left: 5px; border: transparent; background-color: transparent; position: absolute; margin-left: -5px; margin-top: 7px;">
				<img src="{% static 'images/eye-slash-solid.png' %}" alt="顯示密碼" width="20" height="20">
			</button>
		</div>
		<div class="error text-danger">
			<ul>
				{% for field in changePasswordForm %}
				{% for error in field.errors %}
				<li>{{ error }}</li>
				{% endfor %}
				{% endfor %}
			</ul>
		</div>
		<input type="submit" class="btn-submit" value="變更密碼" /><br>
	</form>
	<br>
</div>
<script>
	$(document).ready(function () {
		// 顯示/隱藏 舊密碼
		const password1Input = $("#id_old_password");
		const togglePassword1Button = $("#old_password_eye");
		togglePassword1Button.click(function () {
			if (password1Input.attr("type") === "password") {
				password1Input.attr("type", "text");
				togglePassword1Button.find("img").attr("src", "{% static 'images/eye-solid1.png' %}");
			} else {
				password1Input.attr("type", "password");
				togglePassword1Button.find("img").attr("src", "{% static 'images/eye-slash-solid.png' %}");
			}
		});

		// 顯示/隱藏 新密碼
		const password2Input = $("#id_new_password1");
		const togglePassword2Button = $("#new_password1_eye");
		togglePassword2Button.click(function () {
			if (password2Input.attr("type") === "password") {
				password2Input.attr("type", "text");
				togglePassword2Button.find("img").attr("src", "{% static 'images/eye-solid1.png' %}");
			} else {
				password2Input.attr("type", "password");
				togglePassword2Button.find("img").attr("src", "{% static 'images/eye-slash-solid.png' %}");
			}
		});

		// 顯示/隱藏 新密碼確認
		const password3Input = $("#id_new_password2");
		const togglePassword3Button = $("#new_password2_eye");
		togglePassword3Button.click(function () {
			if (password3Input.attr("type") === "password") {
				password3Input.attr("type", "text");
				togglePassword3Button.find("img").attr("src", "{% static 'images/eye-solid1.png' %}");
			} else {
				password3Input.attr("type", "password");
				togglePassword3Button.find("img").attr("src", "{% static 'images/eye-slash-solid.png' %}");
			}
		});

	});
</script>
{% include 'modal_template.html' %}
{% if success %}
<script>
	$(document).ready(function () {
		alertSuccess('修改密碼', function () {
			window.location.href = "{% url 'Logout' %}";
		});
	});

</script>
{% endif %}
{% endblock %}

AIInterviewBot/templates/accounts/email_error.html
{% extends "accounts/AccountsBase.html" %}

{% block title %}密碼重置請求失敗{% endblock %}

{% block content %}

<body>
    <div class="center w-75" style="box-shadow: none;">
        <h1 style="font-size: 32px;">密碼重置請求失敗</h1>
        <p style="text-align: center;">您提供的電子郵件在我們的系統中不存在。請確保您輸入了正確的電子郵件地址，或者聯繫支援部門以獲得進一步的協助。</p>
        <div style="  display: flex;justify-content: center; ">
            <button class="btn-submit " style="width:80%;" onclick="location.href='/forgot_password/'">
                <span>回上一頁</span>
            </button>
        </div>
        <br>
    </div>
</body>

{% endblock %}

AIInterviewBot/templates/accounts/email_success.html
{% extends "accounts/AccountsBase.html" %}

{% block title %}重置信寄送成功{% endblock %}

{% block content %}

<div class="center w-75" style="box-shadow: none;">
    <h1 style="font-size: 32px;">密碼重置請求已發送</h1>
    <p style="text-align: center;">一封包含重置密碼指示的電子郵件已發送到您的電子郵件地址。請檢查您的收件箱並遵從指示。</p>
    <div style="  display: flex;justify-content: center; ">
        <button class="btn-submit " style="width: 233px;;" onclick="location.href='/login'">
            <span>回上一頁</span>
        </button>
    </div>
    <br>
</div>

{% endblock %}

AIInterviewBot/templates/accounts/forgot_password.html
{% extends "accounts/AccountsBase.html" %}

{% block title %}忘記密碼{% endblock %}

{% block content %}

{% load static %}
<div class="center" style="box-shadow: none;">
    <div style="text-align: center; margin-bottom: 50px;">
        <img src="{% static 'images/LOGO.png' %}" alt="LOGO" width="90" height="108" >
        <h1 style="font-size: 30px; font-weight: 600;">JOBEASE</h1>
    </div>

    <h1 class="forget-password" style="padding-bottom: 0px; text-align: left; padding-left: 40px; font-size: 25px;">忘記密碼</h1>
    <form method="post">
        {% csrf_token %}
        <!-- 忘記密碼表單內容 -->
        <div class="txt_field">
            <div class="input-container">
                <img src="{% static 'images/mail.png' %}" alt="lock" width="18px" height="18px">
                {{ forgotPasswordForm.email }}
                <label for="email" style="margin-left: 8px;">{{ forgotPasswordForm.email.label }}</label>
            </div>
        </div>
        <input type="submit" class="btn-submit" value="重置密碼">
        <br>
        <div style="display: flex;justify-content: center;">
            <a href="{% url 'Login' %}" style="color: #D57F0A; text-decoration: none; font-size: 20px;">取消</a>
        </div>
    </form>
    <br>
</div>

{% include 'modal_template.html' %}
{% if urlExpired %}
<script>
	$(document).ready(function () {
		alertSuccess('密碼重設連結無效或已過期', function () {});
	});
</script>
{% endif %}
{% endblock %}

AIInterviewBot/templates/accounts/problem_report.html
{% extends "base.html" %}
{% block title %}問題回報{% endblock %}
{% block content %}
{% load static %}
<!-- CSS -->
<link rel="stylesheet" type="text/css" href="{% static 'css/problem_report.css' %}" />
<style>
  .form-control::placeholder {
    color: #D9D9D9;
  }

  .form-control {
    color: white;
    background-color: #F7A22D;
  }

  .form-control:focus {
    color: white;
    background-color: #F7A22D;
    outline: none;
    border: 1px solid transparent;
    box-shadow: none;
  }

  .form-control:focus {
    outline: none;
    border: 1px solid transparent;
    box-shadow: none;
  }
  
  #id_problem {
    color: black;
  }
</style>

<h1 class="problem-report" style="color: #F7A32E;">問題回報</h1>
<hr style="background-color: #F7A32E;">
<form method="post">
  {% csrf_token %}
  <div>{{ form.type }}</div>
  <div style="margin-top: 15px">{{ form.problem }}</div>
  <div style="margin-top: 15px; text-align: center;">
    <button type="submit" class="btn btn-primary">送出</button>
  </div>
</form>

{% include 'modal_template.html' %}
{% if success %}
<script>
  $(document).ready(function () {
    alertSuccess('表單送出', function () {
      window.location.href = '{% url "ProblemReport" %}';
    });
  });
</script>
{% endif %}
{% endblock %}

AIInterviewBot/templates/accounts/signup_success_email.html
{{ username }} 您好：

感謝您的註冊!