AIInterviewBot/AIInterviewBot/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import accounts.views as accounts
import contents.views as contents

urlpatterns = [
    # 管理後台
    path('admin/', admin.site.urls),

    # ----------套件 start----------
    
    # 驗證碼
    path('captcha/', include('captcha.urls')),
    #django-allauth
    path('accounts/', include('allauth.urls')),

    # ----------套件 end----------

    # ----------accounts start----------

    # 首頁
    path('', accounts.index, name='Index'),
    # 登入
    path('login/', accounts.sign_in, name='Login'),
    # 登出
    path('logout/',accounts.log_out, name='Logout'),
    # 註冊
    path('register/', accounts.register, name='Register'),
    # 忘記密碼頁面
    path('forgot_password/', accounts.forgot_password, name='ForgotPassword'),
    # 個人檔案頁面
    path('personal/', accounts.personal, name='Personal'),
    # 密碼重設確認頁面
    path('reset/confirm/<uidb64>/<token>/', accounts.password_reset_confirm, name='PasswordResetConfirm'),
    # 密碼重設完成頁面
    path('reset/complete/', accounts.password_reset_complete, name='PasswordResetComplete'),
    # 修改密碼
    path('change_password/', accounts.change_password, name='ChangePassword'),
    # 幫助中心
    path('help_center/', accounts.help_center, name='HelpCenter'),
    # 問題回報
    path('problem_report/', accounts.problem_report, name='ProblemReport'),

    # ----------accounts end------------

    # ----------contents start----------
    
    # 自我介紹
    path('self_introduction/', contents.self_introduction, name='SelfIntroduction'),
    # 求職信
    path('cover_letter/', contents.cover_letter, name='CoverLetter'),
    path('<str:type>/result/', contents.content_result, name='ContentResult'),
    # 推薦信
    path('recommendation_letter/', contents.recommendation_letter, name='RecommendationLetter'),
    # 簡歷
    path('resume/', contents.resume, name='Resume'),
    path('api/download_file/', contents.download_file, name='DownloadFile'),
    # 模擬面試
    path('mock_interview_mode/', contents.mock_interview_mode, name='MockInterviewMode'),
    path('mock_interview/<str:mode>/', contents.mock_interview, name='MockInterview'),
    path('mock_interview_result/', contents.mock_interview_result, name='MockInterviewResult'),
    # 儀錶板
    path('dashboard/', contents.dashboard, name='Dashboard'),
    path('api/get_chart_data/', contents.get_chart_data, name='GetChartData'),
    # 歷史紀錄首頁
    path('history/', contents.history, name='History'),
    # 歷史紀錄詳細頁面
    path('history/detail/', contents.history_detail, name='HistoryDetail'),

    # ----------contents end------------
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AIInterviewBot/contents/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
User = settings.AUTH_USER_MODEL

# 生成結果紀錄
class ContentRecord(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    CONTENT_TYPE_CHOICES = (
        ('CL', '求職信'),
        ('RL', '推薦信'),
        ('SI', '自我介紹'),
    )
    content_type = models.CharField(max_length=10, choices=CONTENT_TYPE_CHOICES)
    unit = models.CharField(max_length=100)
    result = models.TextField()
    is_satisfied = models.BooleanField()
    created_at = models.DateTimeField(auto_now_add=True)

# 個人簡歷生成紀錄
class ResumeRecord(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    personal_education = models.CharField(max_length=100)
    personal_experience = models.TextField()
    skill = models.TextField()
    interest = models.TextField()
    STYLE_CHOICES = (
        ('1', '簡約'),
        ('2', '專業'),
        ('3', '創意'),
    )
    style = models.CharField(max_length=10, choices=STYLE_CHOICES)
    resume_file = models.FileField(upload_to='resume/')
    created_at = models.DateTimeField(auto_now_add=True)

# 模擬面試題庫
class InterviewQuestion(models.Model):
    question = models.CharField(max_length=1000)

    def __str__(self):
        return self.question

# 模擬面試回答紀錄
class InterviewRecord(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(InterviewQuestion, on_delete=models.CASCADE)
    answer = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username + "-" + self.question.question

# 模擬面試評分紀錄
class InterviewScore(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    unit = models.CharField(max_length=100)
    records = models.ManyToManyField(InterviewRecord)
    # 專業能力
    professional_score = models.PositiveIntegerField()
    professional_suggestion = models.TextField()
    # 創意能力
    creative_score = models.PositiveIntegerField()
    creative_suggestion = models.TextField()
    # 策略能力
    strategy_score = models.PositiveIntegerField()
    strategy_suggestion = models.TextField()
    # 溝通能力
    communication_score = models.PositiveIntegerField()
    communication_suggestion = models.TextField()
    # 自主學習能力
    self_learning_score = models.PositiveIntegerField()
    self_learning_suggestion = models.TextField()
    # 綜合能力
    comprehensive_score = models.PositiveIntegerField()
    comprehensive_suggestion = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

# 個人儀錶板
class DashBoard(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    @property
    def score_records(self):
        return InterviewScore.objects.filter(user=self.user)

    @property
    def registration_days(self):
        return (timezone.now() - self.user.date_joined).days

    @property
    def professional_score(self):
        avg_score = InterviewScore.objects.filter(user=self.user).aggregate(models.Avg('professional_score'))['professional_score__avg']
        return round(avg_score, 1) if avg_score else ''
    
    @property
    def creative_score(self):
        avg_score = InterviewScore.objects.filter(user=self.user).aggregate(models.Avg('creative_score'))['creative_score__avg']
        return round(avg_score, 1) if avg_score else ''
    
    @property
    def strategy_score(self):
        avg_score = InterviewScore.objects.filter(user=self.user).aggregate(models.Avg('strategy_score'))['strategy_score__avg']
        return round(avg_score, 1) if avg_score else ''
    
    @property
    def communication_score(self):
        avg_score = InterviewScore.objects.filter(user=self.user).aggregate(models.Avg('communication_score'))['communication_score__avg']
        return round(avg_score, 1) if avg_score else ''
    
    @property
    def self_learning_score(self):
        avg_score = InterviewScore.objects.filter(user=self.user).aggregate(models.Avg('self_learning_score'))['self_learning_score__avg']
        return round(avg_score, 1) if avg_score else ''
    
    @property
    def comprehensive_score(self):
        avg_score = InterviewScore.objects.filter(user=self.user).aggregate(models.Avg('comprehensive_score'))['comprehensive_score__avg']
        return round(avg_score, 1) if avg_score else ''

AIInterviewBot/contents/forms.py
from django import forms
from .models import ResumeRecord
from django.forms import ModelForm

class SelfIntroductionForm(forms.Form):
    company = forms.CharField(
        label="要面試的公司",
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    job = forms.CharField(
        label="要面試的職業",
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    skill1 = forms.CharField(
        label="個人專長1",
        max_length=200,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    skill2 = forms.CharField(
        label="個人專長2",
        max_length=200,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    cultural_fit = forms.CharField(
        label="與要面試的公司文化契合點",
        required=True,
        widget=forms.Textarea(attrs={'class': 'form-control','rows':4, 'cols':5,'style':'resize:none;'})
    )
    cultural_fit_example = forms.CharField(
        label="請列舉文化契合度的實例",
        required=True,
        widget=forms.Textarea(attrs={'class': 'form-control','rows':6, 'cols':5,'style':'resize:none;'})
    )

class CoverLetterForm(forms.Form):
    company = forms.CharField(
        label="想申請的公司名稱",
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    job = forms.CharField(
        label="想應徵的職位名稱",
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    attract = forms.CharField(
        label="想應徵的公司吸引你的原因？",
        required=True,
        widget=forms.Textarea(attrs={'class': 'form-control','rows':4, 'cols':5,'style':'resize:none;'})
    )

    strength = forms.CharField(
        label="你有什麼強項？ 為什麼該公司要選擇你？",
        required=True,
        widget=forms.Textarea(attrs={'class': 'form-control','rows':6, 'cols':5,'style':'resize:none;'})
    )

    example = forms.CharField(
        label="請列舉你的強項",
        required=True,
        widget=forms.Textarea(attrs={'class': 'form-control','rows':6, 'cols':5,'style':'resize:none;'})
    )

class RecommendationLetterForm(forms.Form):
    self = forms.CharField(
        label="被推薦人稱呼",
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    recommender = forms.CharField(
        label="推薦人職稱",
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    position = forms.CharField(
        label="推薦到的單位",
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    experience = forms.CharField(
        label="跟推薦人合作的經驗",
        required=True,
        widget=forms.Textarea(attrs={'class': 'form-control','rows':4, 'cols':5,'style':'resize:none;'})
    )

    reason = forms.CharField(
        label="請列舉值得被推薦的原因",
        required=True,
        widget=forms.Textarea(attrs={'class': 'form-control','rows':4, 'cols':5,'style':'resize:none;'})
    )

STYLE_CHOICES = [
    ('', '請選擇風格'),
    ('1', '簡約'),
    ('2', '專業'),
    ('3', '創意'),
]
class ResumeForm(ModelForm):
    style = forms.ChoiceField(label='簡歷風格', choices=STYLE_CHOICES, widget=forms.Select(attrs={'class': 'form-control'}))
    class Meta:
        model = ResumeRecord
        fields = ['personal_education', 'personal_experience', 'skill', 'interest', 'style']
        widgets = {
            'personal_education': forms.Textarea(attrs={'class': 'form-control','rows':1, 'cols':5,'style':'resize:none;'}),
            'personal_experience': forms.Textarea(attrs={'class': 'form-control','rows':1, 'cols':5,'style':'resize:none;'}),
            'skill': forms.Textarea(attrs={'class': 'form-control','rows':1, 'cols':5,'style':'resize:none;'}),
            'interest': forms.Textarea(attrs={'class': 'form-control','rows':1, 'cols':5,'style':'resize:none;'}),
        }
        labels = {
            'personal_education': '最高學歷',
            'personal_experience': '個人經歷',
            'skill': '專長與技能',
            'interest': '工作外的休閒嗜好',
        }

    
class MockInterviewModeForm(forms.Form):
    company = forms.CharField(
        label="要面試的公司",
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    job = forms.CharField(
        label="要面試的職位",
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    self_introduction = forms.CharField(
        label="個人簡歷",
        required=True,
        widget=forms.Textarea(attrs={'class': 'form-control','rows':10, 'cols':5,'style':'resize:none;'})
    )

    mode = forms.ChoiceField(
        label="選擇模式",
        required=True,
        widget=forms.RadioSelect(attrs={'class': 'form-check-input form-check-inline'}),
        choices=(
            ('1', '單題模式'),
            ('2', '多題模式'),
        )
    )

class MockInterviewForm(forms.Form):
    answer = forms.CharField(
        widget=forms.Textarea(attrs={
            'class': 'form-control',
            'rows': 4, 
            'cols': 5, 
            'style': 'resize: none; background-color: #FCE9CF; width: 90%; height: 108px; margin-top: -10px; margin-left: -10px;',
            'placeholder': '輸入回答'
        })
    )

AIInterviewBot/templates/contents/cover_letter.html
{% extends "base.html" %}
{% block title %}求職信{% endblock %}
{% block content %}
{% load static %}

<div class="container" style="margin-top:10px">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <form id="cover_letter-form" method="post">
                {% csrf_token %}
                <div class="contents-title">
                    求職信輸入
                </div>
                <div class="contents-test">
                    <label>➊{{ form.company.label }}</label>
                    {{ form.company }}
                </div>
                <div class="contents-test">
                    <label>➋{{ form.job.label }}</label>
                    {{ form.job }}
                </div>
                <div class="contents-test">
                    <label>➌{{ form.attract.label }}</label>
                    {{ form.attract }}
                </div>
                <div class="contents-test">
                    <label>➍{{ form.strength.label }}</label>
                    {{ form.strength }}
                </div>
                <div class="contents-test">
                    <label>➎{{ form.example.label }}</label>
                    {{ form.example }}
                </div>
                <div class="GeneratingMessage">
                    <img src="{% static 'images/warning-y.png' %}" alt="Warning" class="warning-icon" style="width: 10px; height: 10px;">
                    生成結果須等待約1分鐘，請勿重新載入頁面
                </div>
                <div class="d-grid col-10 mx-auto">
                    <input type="submit" id="submit-btn" class="btn btn-primary" value="生成求職信" />
                    <button class="btn btn-primary load-btn" type="button" disabled style="display: none">
                        <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true" style="vertical-align: baseline;"></span>
                        生成中...
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

{% include 'modal_template.html' %}
<script>
    $(document).ready(function () {
        $("#cover_letter-form").submit(function (e) {
            e.preventDefault();
            $("#submit-btn").hide();
            $('#id_company, #id_job, #id_attract, #id_strength, #id_example').prop('disabled', true);
            $("#submit-btn").siblings(".load-btn").show();
            $(".GeneratingMessage").show();
            $.ajax({
                url: "{% url 'CoverLetter' %}",
                type: "POST",
                data: {
                    "company": $('#id_company').val(),
                    "job": $('#id_job').val(),
                    "attract": $('#id_attract').val(),
                    "strength": $('#id_strength').val(),
                    "example": $('#id_example').val(),
                    "csrfmiddlewaretoken": "{{ csrf_token }}"
                },
                success: function (response) {
                    if (response.status) {
                        var content_id = response.content_id;
                        window.location.href = "{% url 'ContentResult' 'cover_letter' %}?content_id=" + content_id;
                    }
                },
                error: function (error) {
                    alertFail('生成', function () {
                        window.location.reload();
                    });
                }
            });
        });
    });
</script>
{% endblock %}

AIInterviewBot/templates/contents/recommendation_letter.html
{% extends "base.html" %}
{% block title %}推薦信{% endblock %}
{% block content %}
{% load static %}
<div class="container" style="margin-top:10px">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <form id="recommendation_letter-form" method="post">
                {% csrf_token %}
                <div class="contents-title">
                    推薦信輸入
                </div>
                <div class="contents-test">
                    <label>➊{{ form.self.label }}</label>
                    {{ form.self }}
                </div>
                <div class="contents-test">
                    <label>➋{{ form.recommender.label }}</label>
                    {{ form.recommender }}
                </div>
                <div class="contents-test">
                    <label>➌{{ form.position.label }}</label>
                    {{ form.position }}
                </div>
                <div class="contents-test">
                    <label>➍{{ form.experience.label }}</label>
                    {{ form.experience }}
                </div>
                <div class="contents-test">
                    <label>➎{{ form.reason.label }}</label>
                    {{ form.reason }}
                </div>
                <div class="GeneratingMessage">
                    <img src="{% static 'images/warning-y.png' %}" alt="Warning" class="warning-icon" style="width: 10px; height: 10px;">
                    生成結果須等待約1分鐘，請勿重新載入頁面
                </div>
                <div class="d-grid col-10 mx-auto">
                    <input type="submit" id="submit-btn" class="btn btn-primary" value="生成推薦信" />
                    <button class="btn btn-primary load-btn" type="button" disabled style="display: none">
                        <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true" style="vertical-align: baseline;"></span>
                        生成中...
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

{% include 'modal_template.html' %}
<script>
    $(document).ready(function () {
        $("#recommendation_letter-form").submit(function (e) {
            e.preventDefault();
            $("#submit-btn").hide();
            $('#id_self, #id_recommender, #id_position, #id_experience, #id_reason').prop('disabled', true);
            $("#submit-btn").siblings(".load-btn").show();
            $(".GeneratingMessage").show();
            $.ajax({
                url: "{% url 'RecommendationLetter' %}",
                type: "POST",
                data: {
                    "self": $('#id_self').val(),
                    "recommender": $('#id_recommender').val(),
                    "position": $('#id_position').val(),
                    "experience": $('#id_experience').val(),
                    "reason": $('#id_reason').val(),
                    "csrfmiddlewaretoken": "{{ csrf_token }}"
                },
                success: function (response) {
                    if (response.status) {
                        var content_id = response.content_id;
                        window.location.href = "{% url 'ContentResult' 'recommendation_letter' %}?content_id=" + content_id;
                    }
                },
                error: function (error) {
                    alertFail('生成', function () {
                        window.location.reload();
                    });
                }
            });
        });
    });
</script>
{% endblock %}

AIInterviewBot/templates/contents/resume.html
{% extends "base.html" %}
{% block title %}簡歷{% endblock %}
{% block content %}
{% load static %}
{% load filter %}

<link rel="stylesheet" href="{% static 'css/history.css' %}" type="text/css">

<div class="row justify-content-center">
    <div class="col-md-6 max-auto">
        {% if history %}
        <div class="row">
            <div class="col accounts-title">
                歷史紀錄
            </div>
            <div class="col" style="text-align: end;">
                <img src="{% static 'images/back-y.png' %}" id="back" alt="back" style="width: 35px; height: 35px; cursor: pointer; margin-top: 10px;">
            </div>
            <div class="rpw card detail-card mb-3 border-0" style="background-color: #FFFF"
                data-content-id="{{ record.id }}">
                <div class="row g-0">
                    <div class="col card date-card border-0" style="left: 0px; top: 0px;  background-color: #FCE9CF">
                        <div class="card-body">
                            <h5 class="card-title">{{ record.created_at.day }}</h5>
                            <p class="card-text"><small class="text-muted">{{ record.created_at|get_month_name }}</small></p>
                        </div>
                    </div>
                    <div class="col card bg-transparent border-0">
                        <div class="card-body" style="padding-left: 40px;">
                            <h5 style="color:#5E4104; padding-top: 10px;">{{ record.get_style_display }}簡歷結果</h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        <form id="resumeForm" method="post">
            {% csrf_token %}
            {% if history == false %}
            <div class="contents-title">
                個人簡歷輸入
            </div>
            {% endif%}
            <div class="contents-test">
                <label>➊{{ form.personal_education.label }}</label>
                {{ form.personal_education }}
            </div>
            <div class="contents-test">
                <label>➋{{ form.personal_experience.label }}</label>
                {{ form.personal_experience }}
            </div>
            <div class="contents-test">
                <label>➌{{ form.skill.label }}</label>
                {{ form.skill }}
            </div>
            <div class="contents-test">
                <label>➍{{ form.interest.label }}</label>
                {{ form.interest }}
            </div>
            <div class="contents-test">
                <label>➎{{ form.style.label }}</label>
                {{ form.style }}
            </div>
            <div class="GeneratingMessage">
                <img src="{% static 'images/warning-y.png' %}" alt="Warning" class="warning-icon" style="width: 10px; height: 10px;">
                生成結果須等待約1分鐘，請勿重新載入頁面
            </div>
            <div class="d-grid col-10 mx-auto">
                {% if not history %}
                <input type="submit" id="generate-btn" class="btn btn-primary" value="生成個人簡歷" />
                {% endif %}
                <button id="load-btn" class="btn btn-primary" type="button" disabled style="display: none">
                    <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"
                        style="vertical-align: baseline;"></span>
                    生成中...
                </button>
                <button id="download-btn" class="btn btn-secondary" type="button" style="display: none">
                    <img src="{% static 'images/download.png' %}" alt="download"
                        style="width: 35px; height: 35px; vertical-align: top;">
                    下載簡歷
                </button>
            </div>
        </form>
        <form id="download-form" action="{% url 'DownloadFile' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="file_name" />
        </form>
    </div>
</div>

{% include 'modal_template.html' %}
<script>
    $(document).ready(function () {
        // 判斷是否為歷史紀錄頁面
        var history = '{{ history }}' === 'True';
        if (history) {
            var file_name = '{{ file_name }}';
            downloadMode(file_name);
        }

        $('#resumeForm').submit(function (e) {
            e.preventDefault();
            // 隱藏生成按鈕
            $('#generate-btn').hide();
            // 顯示生成中按鈕
            $('#load-btn').show();
            // 顯示生成中訊息
            $(".GeneratingMessage").show();
            $.ajax({
                url: '{% url "Resume" %}',
                type: 'POST',
                data: $(this).serialize(),
                success: function (data) {
                    downloadMode(data.file_name);
                },
                error: function (error) {
                    alertFail('生成簡歷', function () {
                        window.location.reload();
                    });
                }
            });
        });
        $('#download-btn').click(function (e) {
            $('#download-form').submit();
        });

        $('#back').click(function(){
            window.location.href = "{% url 'History' %}";
        })
        
        // 下載模式
        function downloadMode(fileName) {
            // 隱藏生成按鈕
            $('#generate-btn').hide();
            // 隱藏生成中按鈕
            $('#load-btn').hide();
            // 所有輸入欄位改成禁用
            $('#id_personal_education, #id_personal_experience, #id_skill, #id_interest, #id_style').prop('disabled', true);
            // 設定檔名到隱藏欄位
            $('#download-form input[name=file_name]').val(fileName);
            // 顯示下載按鈕
            $('#download-btn').show();
            // 隱藏生成中訊息
            $(".GeneratingMessage").hide();
        }
    });
</script>

{% endblock %}

AIInterviewBot/templates/contents/self_introduction.html
{% extends "base.html" %}
{% block title %}自我介紹{% endblock %}
{% block content %}
{% load static %}

<div class="container" style="margin-top:10px">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <form id="self_introduction-form" method="post">
                {% csrf_token %}
                <div class="contents-title">
                    自我介紹輸入
                </div>
                <div class="contents-test">
                    <label>➊{{ form.company.label }}</label>
                    {{ form.company }}
                </div>
                <div class="contents-test">
                    <label>➋{{ form.job.label }}</label>
                    {{ form.job }}
                </div>
                <div class="contents-test">
                    <label>➌{{ form.skill1.label }}</label>
                    {{ form.skill1 }}
                </div>
                <div class="contents-test">
                    <label>➍{{ form.skill2.label }}</label>
                    {{ form.skill2 }}
                </div>
                <div class="contents-test">
                    <label>➎{{ form.cultural_fit.label }}</label>
                    {{ form.cultural_fit }}
                </div>
                <div class="contents-test">
                    <label>➏{{ form.cultural_fit_example.label }}</label>
                    {{ form.cultural_fit_example }}
                </div>
                <div class="GeneratingMessage">
                    <img src="{% static 'images/warning-y.png' %}" alt="Warning" class="warning-icon" style="width: 10px; height: 10px;">
                    生成結果須等待約1分鐘，請勿重新載入頁面
                </div>
                <div class="d-grid col-10 mx-auto">
                    <input type="submit" id="submit-btn" class="btn btn-primary" value="生成自我介紹" />
                    <button class="btn btn-primary load-btn" type="button" disabled style="display: none">
                        <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true" style="vertical-align: baseline;"></span>
                        生成中...
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

{% include 'modal_template.html' %}
<script>
    $(document).ready(function () {
        $("#self_introduction-form").submit(function (e) {
            e.preventDefault();
            $("#submit-btn").hide();
            $('#id_company, #id_job, #id_skill1, #id_skill2, #id_cultural_fit, #id_cultural_fit_example').prop('disabled', true);
            $("#submit-btn").siblings(".load-btn").show();
            $(".GeneratingMessage").show();
            $.ajax({
                url: "{% url 'SelfIntroduction' %}",
                type: "POST",
                data: {
                    "company": $('#id_company').val(),
                    "job": $('#id_job').val(),
                    "skill1": $('#id_skill1').val(),
                    "skill2": $('#id_skill2').val(),
                    "cultural_fit": $('#id_cultural_fit').val(),
                    "cultural_fit_example": $('#id_cultural_fit_example').val(),
                    "csrfmiddlewaretoken": "{{ csrf_token }}"
                },
                success: function (response) {
                    if (response.status) {
                        var content_id = response.content_id;
                        window.location.href = "{% url 'ContentResult' 'self_introduction' %}?content_id=" + content_id;
                    }
                },
                error: function (error) {
                    alertFail('生成', function () {
                        window.location.reload();
                    });
                }
            });
        });
    });
</script>
{% endblock %}